### ISSUE TITLE
Animated icons

### ISSUE THREAD

**Issue by dgellow** [alphapeter/fa-svelte#20]
Hi @alphapeter,

Thanks for this library, it's quite handy. I understand that you don't want to support all features from Font Awesome icon sets, but have you considered supporting animated icons?

**Comment by dgellow** [comment]
Hmm, never mind, that's really simple to recreate using CSS animations:
```css
	:global(.spinner) {
		animation: spinner-frames 3s infinite linear;
	}
	@keyframes spinner-frames {
		0% {
			transform: rotate(0deg);
		}
		100% {
			transform: rotate(360deg);
		}
	}
```

Maybe worth documenting in the README :)
